development:
  provider: 'Local'
  local_root: 'tmp/fog'
  directory: 'development'

test:
  provider: 'Local'
  local_root: 'tmp/fog'
  directory: 'test'

production:
  provider: 'AWS'
  aws_access_key_id: '<%= ENV['AWS_ACCESS_KEY_ID'] %>'
  aws_secret_access_key: '<%= ENV['AWS_SECRET_ACCESS_KEY'] %>'
  region: '<%= ENV['AWS_REGION'] || 'us-east-1' %>'
  directory: '<%= ENV['AWS_S3_BUCKET'] %>'
